import Image from 'next/image';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,ArrowUpRight,Check,ChevronDown,HeartPulse,MapPin,ShieldCheck,Stethoscope} from 'lucide-react';
import Header from './Header';
import {medicalPages,sources} from '@/lib/medical-pages';
import {treatments} from '@/lib/data';
import VisualExplainer from './VisualExplainer';

const base='https://fernando-borges-urologia.vercel.app';
const contact=(message)=>'https://wa.me/5566981512722?text='+encodeURIComponent(message);

export default function MedicalTreatmentPage({treatment:t}){
 const p=medicalPages[t.slug];
 const url=base+'/tratamentos/'+t.slug;
 const refs=p.references.map((id)=>sources[id]);
 const isCondition=!['cirurgia-robotica','medicina-sexual-regenerativa','clube-do-check-up','saude-do-homem'].includes(t.slug);
 const schema={'@context':'https://schema.org','@graph':[
  {'@type':'MedicalWebPage','@id':url+'#webpage',url,name:t.title,headline:p.heading,description:p.dek,inLanguage:'pt-BR',dateModified:'2026-09-29',isPartOf:{'@id':base+'/#website'},about:{'@id':url+(isCondition?'#condition':'#care')},publisher:{'@id':base+'/#clinic-rondonopolis'},citation:refs.map((r)=>r[3])},
  ...(isCondition?[{'@type':'MedicalCondition','@id':url+'#condition',name:t.title,description:p.definition}]:[]),
  {'@type':'MedicalProcedure','@id':url+'#care',name:'Avaliação e planejamento de cuidado: '+t.title,description:'Consulta, investigação individualizada e discussão das opções pertinentes.',performer:{'@id':base+'/sobre#physician'},provider:{'@id':base+'/#clinic-rondonopolis'}},
  {'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Início',item:base},{'@type':'ListItem',position:2,name:'Tratamentos',item:base+'/#tratamentos'},{'@type':'ListItem',position:3,name:t.title,item:url}]},
  {'@type':'FAQPage',mainEntity:p.faq.map(([question,answer])=>({'@type':'Question',name:question,acceptedAnswer:{'@type':'Answer',text:answer}}))}
 ]};
 const wa=contact('Olá, gostaria de conversar sobre '+t.title.toLowerCase()+' e agendar uma avaliação.');
 return <main className="medical-page">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/>
  <Header/>
  <section className="med-hero"><div className="med-hero-copy">
   <Link className="med-back" href="/#tratamentos"><ArrowLeft size={17}/> Todos os tratamentos</Link>
   <span className="med-eyebrow">Instituto Fernando Borges <span> / </span> {t.category}</span>
   <h1>{p.heading}</h1><p>{p.dek}</p>
   <div className="med-actions"><a className="med-button med-button-light" href={wa} target="_blank" rel="noopener noreferrer">Fale com nossa equipe <ArrowUpRight size={18}/></a><a className="med-button med-button-outline" href={contact('Olá, gostaria de agendar uma consulta com o Dr. Fernando Borges.')} target="_blank" rel="noopener noreferrer">Agende sua consulta <ArrowRight size={18}/></a></div>
   <small>Informação educativa • Atendimento em Rondonópolis e São Paulo</small>
  </div><div className="med-hero-image"><Image className="med-portrait" src="/dr-fernando-borges-portrait.webp" alt="Dr. Fernando Borges Ribeiro, urologista" width={1122} height={1402} priority sizes="(max-width: 850px) 100vw, 40vw"/><Image className="med-hero-logo" src="/ifb-logo-azul.webp" alt="Instituto Fernando Borges" width={120} height={120}/><div className="med-image-caption"><span>Dr. Fernando Borges Ribeiro</span><small>CRM-MT 4737 · CRM-SP 155372 · RQE 1713 Urologia</small></div></div></section>
  <nav className="med-jump" aria-label="Seções desta página"><a href="#entenda">Entenda</a><a href="#sinais">Sinais</a><a href="#avaliacao">Diagnóstico</a><a href="#opcoes">Tratamentos</a><a href="#duvidas">Dúvidas</a><a href="#fontes">Fontes</a></nav>
  <section className="med-section med-intro" id="entenda"><div className="med-section-label"><span>01 / Entenda</span><HeartPulse/></div><div><h2>O que é {t.title.toLowerCase()}?</h2><p className="med-lead">{p.definition}</p><div className="med-summary"><strong>Em resumo</strong><ul>{p.summary.map((x)=><li key={x}><Check size={17}/>{x}</li>)}</ul></div></div></section>
  <section className="med-section med-pale" id="sinais"><div className="med-section-label"><span>02 / Reconheça</span><Stethoscope/></div><div><h2>{['cirurgia-robotica','clube-do-check-up'].includes(t.slug)?'Quando essa avaliação faz sentido?':'Quais sinais merecem atenção?'}</h2><p>Os sinais orientam a conversa, mas nenhum card substitui uma avaliação individual.</p><div className="med-card-grid">{p.signs.map(([title,summary,detail],i)=><details className="med-sign-card" key={title}><summary><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{summary}</p><span className="med-expand">Saiba mais <ChevronDown size={15}/></span></summary><p>{detail}</p></details>)}</div></div></section>
  <section className="med-section med-dark"><div className="med-section-label"><span>03 / Contexto</span><span className="med-mark">IFB</span></div><div><h2>{['cirurgia-robotica','clube-do-check-up','saude-do-homem'].includes(t.slug)?'Como funciona o cuidado?':'Por que isso acontece?'}</h2><p className="med-lead">{p.mechanism}</p><div className="med-reason-grid">{p.causes.map(([title,detail])=><article key={title}><h3>{title}</h3><p>{detail}</p></article>)}</div></div></section>
  <section className="med-section med-risk"><div className="med-section-label"><span>04 / Fatores</span><ShieldCheck/></div><div><h2>O que pode influenciar o risco?</h2><p>Fatores de risco não são culpa do paciente. Entendê-los ajuda a definir cuidados possíveis.</p><div className="med-risk-grid"><article><h3>Fatores sobre os quais podemos agir</h3><ul>{p.risks.modifiable.map((x)=><li key={x}>{x}</li>)}</ul></article><article><h3>Outros fatores a considerar</h3><ul>{p.risks.other.map((x)=><li key={x}>{x}</li>)}</ul></article></div></div></section>
  <section className="med-section med-pale" id="avaliacao"><div className="med-section-label"><span>05 / Investigação</span><Stethoscope/></div><div><h2>Como é feita a avaliação?</h2><p>Exames complementares entram quando a informação pode modificar o cuidado.</p><ol className="med-timeline">{p.diagnosis.map(([title,detail],i)=><li key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{detail}</p></div></li>)}</ol></div></section>
  <section className="med-section" id="opcoes"><div className="med-section-label"><span>06 / Possibilidades</span><HeartPulse/></div><div><h2>Quais são as opções de cuidado?</h2><p className="med-lead">O melhor tratamento depende do diagnóstico, da gravidade, das características individuais e dos objetivos de cada paciente.</p><div className="med-option-list">{p.options.map(([title,what,when,limits],i)=><details key={title}><summary><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><ChevronDown size={20}/></summary><div className="med-option-content"><p><strong>O que é</strong>{what}</p><p><strong>Quando considerar</strong>{when}</p><p><strong>Limites e riscos</strong>{limits}</p></div></details>)}</div>{p.special&&<blockquote>{p.special}</blockquote>}</div></section>
  <VisualExplainer slug={t.slug}/>
  <section className="med-authority"><div className="med-authority-photo"><Image src="/dr-fernando-borges-portrait.webp" alt="Retrato do Dr. Fernando Borges Ribeiro" width={1122} height={1402} sizes="(max-width: 850px) 100vw, 35vw" loading="lazy"/></div><div><span className="med-eyebrow med-eyebrow-dark">O especialista</span><h2>Informação médica com experiência clínica.</h2><p>Dr. Fernando Borges Ribeiro atua em Urologia e Cirurgia Geral, com cuidado individualizado em saúde masculina. Uma consulta considera sintomas, contexto de saúde, exames pertinentes e alternativas para decidir junto com o paciente.</p><p className="med-credentials">CRM-MT 4737 · CRM-SP 155372<br/>RQE 1713 Urologia · RQE 1451 Cirurgia Geral</p><Link href="/sobre">Conheça o Dr. Fernando Borges <ArrowUpRight size={18}/></Link></div></section>
  <section className="med-section med-attention"><div className="med-section-label"><span>07 / Orientação</span><ShieldCheck/></div><div><h2>Quando procurar um médico?</h2><div className="med-attention-grid"><article><span>Vale marcar uma avaliação</span><p>{p.attention.routine}</p></article><article><span>Procure atendimento com maior urgência se...</span><p>{p.attention.urgent}</p></article></div></div></section>
  <section className="med-section med-pale"><div className="med-section-label"><span>08 / Esclareça</span><HeartPulse/></div><div><h2>Mitos e verdades</h2><div className="med-myth-grid">{p.myths.map(([myth,truth])=><details key={myth}><summary><small>MITO</small><h3>{myth}</h3><span>Ver explicação <ChevronDown size={16}/></span></summary><p><strong>Na prática:</strong> {truth}</p></details>)}</div></div></section>
  <section className="med-section med-faq" id="duvidas"><div className="med-section-label"><span>09 / Perguntas</span><Stethoscope/></div><div><h2>Perguntas frequentes</h2><div>{p.faq.map(([question,answer])=><details key={question}><summary>{question}<ChevronDown size={19}/></summary><p>{answer}</p></details>)}</div></div></section>
  <section className="med-cta"><span>Uma conversa pode ajudar a entender o próximo passo.</span><h2>Cuide da sua saúde com uma avaliação individual.</h2><p>Converse com a equipe para agendar uma consulta. As opções de cuidado serão discutidas de acordo com o seu caso.</p><div className="med-actions"><a className="med-button med-button-light" href={wa} target="_blank" rel="noopener noreferrer">Fale agora com nossa equipe <ArrowUpRight size={18}/></a><a className="med-button med-button-outline" href={contact('Olá, gostaria de agendar uma consulta com o Dr. Fernando Borges.')} target="_blank" rel="noopener noreferrer">Agende sua consulta <ArrowUpRight size={18}/></a></div><p className="med-location"><MapPin size={17}/> Rondonópolis · São Paulo</p></section>
  <section className="med-section med-sources" id="fontes"><div className="med-section-label"><span>10 / Evidência</span><ShieldCheck/></div><div><details><summary>Fontes e referências científicas <ChevronDown size={18}/></summary><ol>{refs.map(([institution,title,year,link])=><li key={link}><a href={link} target="_blank" rel="noopener noreferrer">{institution}. <em>{title}</em>. {year}. <ArrowUpRight size={14}/></a></li>)}</ol></details><p className="medical-notice">{t.notice} Fontes consultadas para a redação em setembro de 2026. Este conteúdo educativo não é um diagnóstico individual.</p></div></section>
  <nav className="med-related" aria-label="Outras páginas de cuidado"><span>Continue explorando</span>{p.related.map((slug)=>{const item=treatments.find((x)=>x.slug===slug);return item&&<Link href={'/tratamentos/'+slug} key={slug}>{item.title} <ArrowUpRight size={16}/></Link>})}</nav>
  <a className="med-mobile-cta" href={wa} target="_blank" rel="noopener noreferrer">Agendar avaliação <ArrowUpRight size={17}/></a>
 </main>;
}
