'use client';
import Link from 'next/link';
import { motion,useScroll,useTransform } from 'framer-motion';
import { ArrowDown,ArrowUpRight,Award,Bot,CheckCircle2,Gem,HeartPulse,MapPin,ScanLine,ShieldCheck,Sprout,Star,Instagram,Phone,Mail } from 'lucide-react';
import Header from './Header'; import Reveal from './Reveal'; import {treatments} from '@/lib/data';
const icons={Bot,ShieldCheck,Gem,ScanLine,HeartPulse,Sprout};
export default function Site(){const {scrollYProgress}=useScroll();const scaleX=useTransform(scrollYProgress,[0,1],[0,1]);return <main><motion.div className="progress" style={{scaleX}}/><Header dark/>
<section className="hero"><div className="hero-grid"/><div className="hero-glow"/><div className="hero-content"><motion.p className="kicker" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.2}}>Urologia • Cirurgia Robótica • Uro-oncologia</motion.p><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.35,duration:.9}}>Precisão para cuidar.<br/><em>Presença para acolher.</em></motion.h1><motion.p className="hero-copy" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.55}}>Tecnologia avançada, experiência cirúrgica e um olhar verdadeiramente humano em cada etapa do cuidado.</motion.p><motion.div className="hero-actions" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.75}}><a className="btn btn-gold" href="https://wa.me/556696457535?text=Olá%2C%20gostaria%20de%20agendar%20uma%20consulta." target="_blank">Agendar consulta <ArrowUpRight size={18}/></a><a className="btn btn-ghost" href="#sobre">Conheça o Dr. Fernando <ArrowDown size={17}/></a></motion.div></div><div className="hero-stats"><div><b>20+</b><span>anos de experiência</span></div><div><b>1º</b><span>cirurgião robótico certificado de Rondonópolis</span></div><div><b>2</b><span>cidades de atendimento</span></div></div></section>
<section className="manifest"><Reveal><p>“Conheça todas as teorias, domine todas as técnicas, mas ao tocar uma alma humana, seja apenas outra alma humana.”</p><span>— Carl G. Jung</span></Reveal></section>
<section className="about section" id="sobre"><div className="section-tag">01 — O especialista</div><div className="about-grid"><Reveal className="about-visual"><div className="portrait-placeholder"><span>Dr.</span><b>Fernando<br/>Borges Ribeiro</b><small>CRM-MT 4737 • RQE 1713</small></div><div className="seal"><Award/><span>Certificação<br/>Internacional</span></div></Reveal><div><Reveal><p className="eyebrow">Experiência que evolui. Cuidado que permanece.</p><h2>Excelência técnica com uma visão <em>integral</em> do paciente.</h2></Reveal><Reveal delay={.1}><p className="lead">Urologista, cirurgião e pioneiro em técnicas minimamente invasivas na região de Rondonópolis.</p><p>Graduado pela Universidade Estadual de Maringá, com residências em Cirurgia Geral e Urologia pela Universidade Estadual de Londrina. Especializou-se em Urologia Minimamente Invasiva no Hospital Sírio-Libanês e em Cirurgia Robótica Urológica no Hospital Albert Einstein.</p></Reveal><Reveal className="credentials" delay={.2}><div><b>2000</b><span>Graduação em Medicina</span></div><div><b>2005</b><span>Início da atuação em Rondonópolis</span></div><div><b>2021</b><span>Certificação em Cirurgia Robótica</span></div></Reveal></div></div></section>
<section className="treatments section" id="tratamentos"><div className="section-tag light">02 — Áreas de atuação</div><Reveal><p className="eyebrow gold">Cuidado especializado</p><h2>Soluções modernas para cada <em>momento da vida.</em></h2></Reveal><div className="treatment-grid">{treatments.map((t,i)=>{const I=icons[t.icon];return <Reveal key={t.slug} delay={i*.06}><Link href={`/tratamentos/${t.slug}`} className="treatment-card"><span className="card-num">0{i+1}</span><I/><small>{t.eyebrow}</small><h3>{t.title}</h3><p>{t.desc}</p><span className="card-link">Saiba mais <ArrowUpRight size={17}/></span></Link></Reveal>})}</div></section>
<section className="difference section" id="estrutura"><div className="section-tag">03 — UROLASER</div><div className="difference-grid"><div><Reveal><p className="eyebrow">Tudo em um só lugar</p><h2>Estrutura completa. Atendimento <em>sem atalhos.</em></h2><p className="lead">Um centro urológico pensado para oferecer agilidade, segurança e conforto — da consulta ao tratamento.</p></Reveal><div className="check-list">{['Consultas urológicas','Ultrassom urológico','Biópsia de próstata','Cistoscopia e urodinâmica','Litotripsia e pequenas cirurgias','Equipe especializada e acolhedora'].map((x,i)=><Reveal key={x} delay={i*.05}><div><CheckCircle2/>{x}</div></Reveal>)}</div></div><Reveal className="tech-panel"><div className="orb"><div/><div/><span>Precisão<br/><b>em cada detalhe</b></span></div><div className="tech-caption"><Star/><p>“Tecnologia só faz sentido quando amplia nossa capacidade de cuidar.”</p></div></Reveal></div></section>
<section className="locations section" id="contato"><div className="section-tag light">04 — Onde estou</div><Reveal><p className="eyebrow gold">Duas cidades, o mesmo cuidado</p><h2>Escolha a unidade mais <em>perto de você.</em></h2></Reveal><div className="location-grid"><Reveal className="location-card main-location"><span>Unidade principal</span><MapPin/><h3>Rondonópolis — MT</h3><p>UROLASER Centro Urológico<br/>Rua José Salmen, 603 — Vila Birigui<br/>CEP 78705-057</p><div className="phone-row"><Phone/> +55 (66) 9645-7535<br/>(66) 3426-8651</div><a href="https://maps.google.com/?q=Rua+José+Salmen+603+Rondonópolis+MT" target="_blank">Ver no mapa <ArrowUpRight size={16}/></a></Reveal><Reveal className="location-card" delay={.12}><span>Unidade São Paulo</span><MapPin/><h3>São Paulo — SP</h3><p>Brascam<br/>Rua Joaquim Floriano, 466 — 14º andar<br/>Itaim Bibi • CEP 04534-002</p><div className="phone-row"><Phone/> (11) 99840-0066</div><a href="https://maps.google.com/?q=Rua+Joaquim+Floriano+466+São+Paulo" target="_blank">Ver no mapa <ArrowUpRight size={16}/></a></Reveal></div></section>
<section className="cta-section"><Reveal><p>Seu cuidado pode começar agora.</p><h2>Converse com nossa equipe.</h2><a className="btn btn-gold" href="https://wa.me/556696457535?text=Olá%2C%20gostaria%20de%20agendar%20uma%20consulta." target="_blank">Agendar pelo WhatsApp <ArrowUpRight/></a></Reveal></section><Footer/></main>}
function Footer(){return <footer><div className="footer-brand"><span className="brand-mark">FB</span><div><b>Dr. Fernando Borges Ribeiro</b><small>Urologia • Cirurgia Robótica</small></div></div><div><h4>Contato</h4><a href="tel:+556696457535"><Phone/> +55 (66) 9645-7535</a><a href="mailto:contato@fernandoborgesribeiro.com.br"><Mail/> contato@fernandoborgesribeiro.com.br</a></div><div><h4>Acompanhe</h4><a href="https://www.instagram.com/fernandoborges.uro/" target="_blank"><Instagram/> @fernandoborges.uro</a></div><div className="footer-bottom"><span>CRM-MT 4737 • CRM-SP 155372 • RQE 1451 Cirurgia Geral • RQE 1713 Urologia</span><span>© {new Date().getFullYear()} Dr. Fernando Borges Ribeiro</span></div></footer>}
